- name: Create mysql backup directory
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    mode: 0755
    owner: backup

- name: MySQL user for backup
  community.mysql.mysql_user:
    name: "{{ mysql_backup_user }}"
    password: "{{ mysql_backup_pass }}"
    priv: 
      'agama.*': 'LOCK TABLES,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Change my.cnf mysql config
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: 0400

- name: Copy mysql backup crontab file
  ansible.builtin.template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup