- name: Stop and disable resolv
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Change resolv config
  ansible.builtin.template:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/resolv/templates/resolv.conf.j2
    dest: /etc/resolv.conf
