- name: Install nginx
  apt:
    name: nginx
    update_cache: yes

- name: Change nginx main page
  ansible.builtin.copy:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/nginx/files/index.html
    dest: /var/www/html/index.html

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Change nginx config
  ansible.builtin.copy:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/nginx/files/default
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart nginx