- name: Install nginx
  apt:
    name: nginx
    update_cache: yes

- name: Change nginx main page
  ansible.builtin.copy:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/nginx/files/index.html
    dest: /var/www/html/index.html