- name: Install nginx
  apt:
    name: nginx

- name: Change nginx main page
  ansible.builtin.copy:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/nginx/files/index.html
    dest: /var/www/html/index.html

- name: Change nginx config
  ansible.builtin.template:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/nginx/templates/default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart nginx

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes