- name: Init
  hosts: all
  become: yes
  roles:
    - init

- name: DB 1
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - influxdb

- name: DNS 1
  hosts: dns_servers
  become: yes
  roles:
    - bind
    - bind_exporter

- name: Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus

- name: All 1
  hosts: all
  become: yes
  roles:
    - resolv
    - docker_fix
    - docker
    - agama
    - node_exporter
    - nginx
    - nginx_exporter
    - rsyslog
    - backup

- name: Grafana
  hosts: grafana
  become: yes
  roles:
    - docker
    - grafana

- name: Pinger
  hosts: pinger
  become: yes
  roles:
    - pinger

- name: DB 2
  hosts: db_servers
  become: yes
  roles:
    - mysql_exporter
    - influxdb_exporter
    - mysql_backup
    - influxdb_backup

- name: Haproxy/Keepalived
  hosts: all
  become: yes
  roles:
    - keepalived
    - haproxy
    - keepalived_exporter
    - haproxy_exporter
