- name: Init
  hosts: all
  become: yes
  roles:
    - init

- name: Database/DNS server
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - bind

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
    - prometheus

- name: All
  hosts: all
  become: yes
  roles:
    - node_exporter
    - nginx
    - resolv
    - nginx_exporter
    - rsyslog
    - backup

- name: Database/DNS server
  hosts: db_servers
  become: yes
  roles:
    - mysql_exporter
    - bind_exporter
    - grafana
    - influxdb
    - pinger
    - influxdb_exporter
