- name: All
  hosts: all
  become: yes
  roles:
    - init
    - node_exporter
    - nginx
    - resolv

- name: Database/DNS server
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - bind

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
    - nginx
    - prometheus