# - name: Init
#   hosts: all
#   become: yes
#   roles:
#     - init

# - name: DNS Servers
#   hosts: dns_servers
#   become: yes
#   roles:
#     - bind
#     - bind_exporter

# - name: Resolv
#   hosts: all
#   become: yes
#   roles:
#     - resolv

# - name: Prometheus
#   hosts: prometheus
#   become: yes
#   roles:
#     - prometheus

# - name: MySQL
#   hosts: mysql
#   become: yes
#   roles:
#     - mysql
#     - mysql_exporter
#     - mysql_backup

# - name: InfluxDB
#   hosts: influxdb
#   become: yes
#   roles:
#     - influxdb
#     - influxdb_exporter
#     - influxdb_backup

# - name: All 1
#   hosts: all
#   become: yes
#   roles:
#     - docker_fix
#     - docker
#     - agama
#     - node_exporter
#     - nginx
#     - nginx_exporter
#     - rsyslog
#     - backup

# - name: Grafana
#   hosts: grafana
#   become: yes
#   roles:
#     - docker
#     - grafana

# - name: Pinger
#   hosts: pinger
#   become: yes
#   roles:
#     - pinger 
# - name: Haproxy/Keepalived
#   hosts: all
#   become: yes
#   roles:
#     - keepalived
#     - haproxy
#     - keepalived_exporter
#     - haproxy_exporter


# ================
# ===== All =====

- name: Init
  hosts: all
  become: yes
  roles:
    - init

- name: Node Exporter
  hosts: all
  become: yes
  roles:
    - node_exporter
  tags: node

- name: Rsyslog
  hosts: all
  become: yes
  roles:
    - rsyslog
  tags: rsyslog

# ===== DNS Setup =====

- name: Bind9
  hosts: all
  become: yes
  roles:
    - bind
    - bind_exporter
    - resolv
  tags: bind

# ===== Int Services =====

- name: InfluxDB and Telegraf
  hosts: int_serv
  become: yes
  roles:
    - influxdb
    - influxdb_exporter
    - influxdb_backup
  tags: influx

- name: pinger
  hosts: int_serv
  become: yes
  roles:
    - pinger
  tags: pinger

- name: Prometheus
  hosts: int_serv
  become: yes
  roles:
    - prometheus
  tags: prom

- name: Docker at Int Serv
  hosts: int_serv
  become: yes
  roles:
    - docker_fix
    - docker
  tags: dockserv

- name: Grafana
  hosts: int_serv
  become: yes
  roles:
    - grafana
  tags: graf

- name: Nginx at Int Serv
  hosts: int_serv
  become: yes
  roles:
    - nginx
    - nginx_exporter
  tags: ngserv

# ===== App Stack =====

- name: Keepallived
  hosts: app_stack
  become: yes
  roles:
    - keepalived
    - keepalived_exporter
  tags: hap

- name: Haproxy
  hosts: app_stack
  become: yes
  roles:
    - haproxy
    - haproxy_exporter
  tags: keep

- name: Docker at App Stack
  hosts: app_stack
  become: yes
  roles:
    - docker_fix
    - docker
  tags: dockapp

- name: Agama
  hosts: app_stack
  become: yes
  roles:
    - agama
  tags: agama

- name: MySQL
  hosts: app_stack
  become: yes
  roles:
    - mysql
    - mysql_exporter
    - mysql_backup
  tags: mysql

- name: Nginx at App Stack
  hosts: app_stack
  become: yes
  roles:
    - nginx
    - nginx_exporter
  tags: ngapp

