- name: All
  hosts: all
  become: yes
  roles:
    - init
    - node_exporter
    - nginx
    - resolv

- name: Database/DNS server
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - bind
<<<<<<< HEAD

- name: All
  hosts: all
  become: yes
  roles:
    - node_exporter
    - resolv
=======
>>>>>>> 0ce7e493b3502adad0a16ffb611b74981814de65

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
    - nginx
    - prometheus