{
 "title": "MySQL",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"remote1:9104\"}",
     "legendFormat": "remote1"
    },
    {
     "expr": "mysql_up{instance=\"remote2:9104\"}",
     "legendFormat": "remote2"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{}[1m])"
    }
   ]
  },
  {
   "title": "IDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{instance=\"remote1:9104\"}",
     "legendFormat": "remote1"
    },
    {
     "expr": "mysql_global_variables_server_id{instance=\"remote2:9104\"}",
     "legendFormat": "remote2"
    }
   ]
  },
  {
   "title": "Read Only Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=\"remote1:9104\"}",
     "legendFormat": "remote1"
    },
    {
     "expr": "mysql_global_variables_read_only{instance=\"remote2:9104\"}",
     "legendFormat": "remote2"
    }
   ]
  },
  {
   "title": "Slave IO and SQL Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running "
    },
    {
     "expr": "mysql_slave_status_slave_sql_running"
    }
   ]
  }
 ]
}