- name: Create agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Get agama
  get_url:
    url: https://github.com/hudolejev/agama/raw/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Build agama docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Create agama container
  community.docker.docker_container:
    name: agama
    image: agama
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
    published_ports: "{{ agama_port }}:8000"