- name: Add user "backup"
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    
- name: Create restore directory
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    mode: 0755
    owner: backup

- name: Install duplicity
  apt:
    name: duplicity

- name: Copy known hosts file
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup