- name: Add user "backup"
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    move_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Create restore directory
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    mode: '0755'
    owner: backup

- name: Install duplicity
  apt:
    name: duplicity

- name: Copy pinger config
  ansible.builtin.template:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/backup/templates/known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup

- name: MySQL user for backup
  community.mysql.mysql_user:
    name: "backup"
    password: "{{ mysql_password }}"
    host: "{{ mysql_host }}"
    priv: 
      '*.*': 'LOCK TABLES,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Change mysql config
  ansible.builtin.template:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/backup/templates/my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: '0700'
