- name: Add user "backup"
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    move_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa