- name: Create influxdb backup directory
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    mode: '0755'
    owner: backup

- name: Copy crontab file
  ansible.builtin.templates:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/influxdb_backup/files/influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup
