- name: Create influxdb backup directory
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    mode: '0755'
    owner: backup

#- name: Create influxdb directory on backup server
#  ansible.builtin.shell:
#    cmd: sudo -u backup ssh {{ github_username }}@backup.{{ domain }}.{{ tld }} mkdir -p ./influxdb
#  when: hostvars[inventory_hostname]['ansible_default_ipv4']['address'] == mysql_host

- name: Copy crontab file
  ansible.builtin.template:
    src: influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup
