- name: Copy iptables config
  ansible.builtin.copy:
    src: iptables.mangle
    dest: /var/local/iptables.mangle

- name: Restore iptables
  community.general.iptables_state:
    path: /var/local/iptables.mangle
    state: restored
    table: mangle