- name: Install mysql exporter
  apt:
    name: prometheus-mysqld-exporter

- name: MySQL user for mysql exporter
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    host: "%"
    priv: 
      '*.*': 'PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Change mysql config
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify:
    - Restart mysql exporter

- name: Copy mysqld exp file
  ansible.builtin.copy:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify:
    - Restart mysql exporter

- name: Start and enable mysql exporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes