- name: Install mysql
  apt:
    name: mysql-server

- name: Install pymysql
  apt:
    name: python3-pymysql

- name: Change mysql config
  ansible.builtin.template:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
    - Restart mysql

- name: Start and enable mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL agama user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: MySQL replication user
  community.mysql.mysql_user:
    name: "{{ mysql_repl_user }}"
    password: "{{ mysql_repl_pass }}"
    host: "%"
    priv: 
      '*.*': 'REPLICATION SLAVE'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: MySQL replica read only
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if hostvars[inventory_hostname]['ansible_default_ipv4']['address'] == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
      - Reset MySQL source
      - Reset MySQL replica
