- name: Add user "pinger"
  ansible.builtin.user:
    name: pinger

- name: Install fping
  apt:
    name: fping

- name: Create pinger directory
  ansible.builtin.file:
    path: /etc/pinger
    state: directory
    mode: '0755'

- name: Copy pinger shell file
  ansible.builtin.copy:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/pinger/files/pinger.sh
    dest: /usr/local/bin/pinger
    mode: a+x

- name: Copy pinger service file
  ansible.builtin.copy:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/pinger/files/pinger.service
    dest: /etc/systemd/system/pinger.service
    mode: a+x
  notify:
    - Reload systemd

- name: Copy pinger config
  ansible.builtin.template:
    src: /home/tengz/Documents/GitVSC/ica0002/roles/pinger/templates/pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify:
    - Restart pinger

- name: Start and enable pinger
  ansible.builtin.service:
    name: pinger
    state: started
    enabled: yes