- name: Add user "keepalived_script"
  ansible.builtin.user:
    name: keepalived_script
    home: /home/keepalived_script

- name: Install keepalived
  apt:
    name: keepalived

- name: Change keepalived config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
    - Restart keepalived

- name: Copy keepalived script file
  ansible.builtin.copy:
    src: vrrp_script.sh
    dest: /home/keepalived_script/vrrp_script
    owner: keepalived_script
    mode: a+x
  notify:
    - Restart keepalived

- name: Start and enable keepalived
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: yes
