- name: Install nginx exporter
  apt:
    name: prometheus-nginx-exporter

- name: Start and enable nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes

- name: Change nginx config for exporter
  ansible.builtin.copy:
    src: exporter
    dest: /etc/nginx/sites-enabled/exporter
  notify:
    - Restart nginx exporter