- name: Install docker
  apt:
    name: docker.io

- name: Install python3 docker
  apt:
    name: python3-docker

- name: Start and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Log into Docker
  community.docker.docker_login:
    username: "{{ docker_login }}"
    password: "{{ docker_pass }}"
    