- name: Restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: hostvars[inventory_hostname]['ansible_default_ipv4']['address'] == mysql_host

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host }}"
    primary_user: "{{ mysql_repl_user }}"
    primary_password: "{{ mysql_repl_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: hostvars[inventory_hostname]['ansible_default_ipv4']['address'] != mysql_host
  no_log: true